# Generated by Django 5.2.17 on 2026-08-21 09:26

import apps.accounts.validators
import apps.common.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Creator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('channel_name', models.CharField(max_length=150)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('skills', models.JSONField(blank=True, default=list, validators=[apps.accounts.validators.validate_skill_list])),
                ('hourly_rate', apps.common.fields.PositiveMoneyField(decimal_places=2, max_digits=12)),
                ('availability_status', models.CharField(choices=[('available', 'Available'), ('busy', 'Busy'), ('inactive', 'Inactive')], db_index=True, default='available', max_length=16)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'constraints': [models.CheckConstraint(condition=models.Q(('hourly_rate__gt', 0)), name='supplier_hourly_rate_positive')],
            },
        ),
    ]
