# Generated by Django 5.2.17 on 2026-08-21 09:46

import apps.common.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('budget', apps.common.fields.PositiveMoneyField(decimal_places=2, max_digits=12)),
                ('category', models.CharField(db_index=True, max_length=50)),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], db_index=True, default='open', max_length=16)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='gigs', to='accounts.creator')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'constraints': [models.CheckConstraint(condition=models.Q(('budget__gt', 0)), name='gig_budget_positive')],
            },
        ),
    ]
