# Generated by Django 5.2.17 on 2026-08-21 09:59

import apps.common.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('gigs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('proposed_rate', apps.common.fields.PositiveMoneyField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn')], default='pending', max_length=16)),
                ('gig', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='gigs.gig')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applications', to='accounts.supplier')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['gig', 'status'], name='application_gig_status_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('proposed_rate__gt', 0)), name='application_proposed_rate_positive'), models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('gig', 'supplier'), name='unique_pending_application_per_gig_and_supplier')],
            },
        ),
    ]
