# Generated by Django 5.2.17 on 2026-08-21 10:21

import apps.common.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('gigs', '0001_initial'),
        ('hiring', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agreed_rate', apps.common.fields.PositiveMoneyField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('terminated', 'Terminated')], default='active', max_length=16)),
                ('gig', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contracts', to='gigs.gig')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contracts', to='accounts.supplier')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['supplier', 'status'], name='contract_supplier_status_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('agreed_rate__gt', 0)), name='contract_agreed_rate_positive'), models.UniqueConstraint(condition=models.Q(('status', 'active')), fields=('gig',), name='unique_active_contract_per_gig')],
            },
        ),
    ]
