# Generated by Django 5.2.17 on 2026-08-21 18:22

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hiring', '0002_contract'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewer_type', models.CharField(choices=[('creator_on_supplier', 'Creator on supplier'), ('supplier_on_creator', 'Supplier on creator')], max_length=32)),
                ('rating', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comment', models.TextField(blank=True, default='')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reviews', to='hiring.contract')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'constraints': [models.UniqueConstraint(fields=('contract', 'reviewer_type'), name='unique_review_per_contract_and_reviewer_type'), models.CheckConstraint(condition=models.Q(('rating__gte', 1), ('rating__lte', 5)), name='review_rating_within_range')],
            },
        ),
    ]
